<?php

namespace DelOlmo\Token\Generator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-11-22 at 15:11:14.
 */
class UriSafeTokenGeneratorTest extends \PHPUnit_Framework_TestCase
{

    const ENTROPY = 1000;

    /**
     * @var UriSafeTokenGenerator
     */
    protected $generator;

    protected function setUp()
    {
        $this->generator = new UriSafeTokenGenerator(self::ENTROPY);
    }

    protected function tearDown()
    {
        $this->generator = null;
    }

    public function testGenerateToken()
    {
        $token = $this->generator->generateToken();
        $this->assertTrue(ctype_print($token), 'is printable');
        $this->assertStringNotMatchesFormat('%S+%S', $token, 'is URI safe');
        $this->assertStringNotMatchesFormat('%S/%S', $token, 'is URI safe');
        $this->assertStringNotMatchesFormat('%S=%S', $token, 'is URI safe');
    }

}
