<?php

namespace DelOlmo\Token;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-11-22 at 15:11:10.
 */
class TokenTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var \DelOlmo\Token\Token
     */
    protected $token;

    protected function setUp()
    {
        $this->token = new Token('foo', 'bar');
    }

    protected function tearDown()
    {
        $this->token = null;
    }

    /**
     * @covers DelOlmo\Token\Token::__toString
     */
    public function test__toString()
    {
        $this->assertEquals((string) $this->token, 'bar');
    }

    /**
     * @covers DelOlmo\Token\Token::getId
     */
    public function testGetId()
    {
        $this->assertEquals($this->token->getId(), 'foo');
    }

    /**
     * @covers DelOlmo\Token\Token::getValue
     */
    public function testGetValue()
    {
        $this->assertEquals($this->token->getValue(), 'bar');
    }

}
