<?php

namespace DelOlmo\Token\Encoder;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-11-22 at 15:11:10.
 */
class DummyTokenEncoderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var \DelOlmo\Token\Encoder\DummyTokenEncoder
     */
    protected $encoder;

    protected function setUp()
    {
        $this->encoder = new DummyTokenEncoder();
    }

    protected function tearDown()
    {
        $this->encoder = null;
    }

    public function testHashAndValidation()
    {
        $hash = $this->encoder->hash('foo');
        $this->assertTrue($this->encoder->verify('foo', $hash));
        $this->assertTrue($this->encoder->verify($hash, 'foo'));
    }

}
