<?php

namespace DelOlmo\Token\Encoder;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-11-22 at 15:11:11.
 */
class NativePasswordTokenEncoderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var NativePasswordTokenEncoder
     */
    protected $encoder;

    protected function setUp()
    {
        $this->encoder = new NativePasswordTokenEncoder();
    }

    protected function tearDown()
    {
        $this->encoder = null;
    }

    public function testHashAndValidation()
    {
        $hash = $this->encoder->hash('foo');
        $this->assertTrue($this->encoder->verify('foo', $hash));
    }

}
